POST http://localhost:5000/api/user
Content-Type: application/json

{
 "firstName": "William",
 "lastName": "Shakespeare",
 "email": "toBeeOrNottoBeeee@question.co.uk",
 "password": "Password12!"
}

###

GET http://localhost:5000/api/users-list

###

GET http://localhost:5000/api/items-list

###

GET http://localhost:5000/api/user/62b0ec582ee156fe56d87e0c

###

PUT http://localhost:5000/api/user/62b0ec582ee156fe56d86e0c
Content-Type: application/json

{
    "firstName": "Bill"
}

###

DELETE http://localhost:5000/api/user/62e02a666bac6c49e333768a
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTAyYTY2NmJhYzZjNDllMzMzNzY4YSIsImVtYWlsIjoicm9kcmlnby5jYXN0ZWxAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IlJvZHJpZ28iLCJ0eXBlIjoiQWRtaW4iLCJpYXQiOjE2NjExMjMyNDMsImV4cCI6MTY2MTIwOTY0M30.-M-rpcQbP407Gc3AjTw65kvmHpX3bEMBvjocJQzwBjM

###

POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "rodrigo.castel@gmail.com",
    "password": "Password123!"
}

###

GET https://fakestoreapi.com/products